apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ctkk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-ctkk@sha256:08998e8218b10cabc75ef4d102313023e11e8b740fc7a322b82a9f7407b82bc4
        name: my-nodejs
        resources: {}
status: {}
